// generated by fcompile.codegen.CCodeGen at 2023-10-14 00:41:19
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include <faccel.h>

static uint8_t* input_x;
static const uint8_t* const_w1;
static struct Mapped_Weight* accel_wmap_1;
static const uint8_t* const_w2;
static struct Mapped_Weight* accel_wmap_3;
static uint8_t* op_5;
static uint8_t* op_6;
void tvm_extern6(void*, int32_t*);

void TVMWrapInit() {
  input_x = (uint8_t*)malloc(2352);
  accel_wmap_1 = Malloc_Weight(3, 3, 3, 32, 5, 8);
  accel_wmap_3 = Malloc_Weight(3, 3, 32, 64, 5, 8);
  op_5 = (uint8_t*)malloc(36864);
  op_6 = (uint8_t*)malloc(36864);
}

void TVMWrapSetParams(char* params) {
  const_w1 = (uint8_t*)params; params += 18432;
  Map_Weight((char*)const_w1, accel_wmap_1);
  const_w2 = (uint8_t*)params; params += 36864;
  Map_Weight((char*)const_w2, accel_wmap_3);
}

// input 0: (1, 28, 28, 3)
void* TVMWrapGetInputPtr(int index) {
  uintptr_t array_ptr[1] = { (uintptr_t)input_x };
  return (void*)array_ptr[index];
}

// output 0: (1, 64, 24, 24)
void* TVMWrapGetOutputPtr(int index) {
  uintptr_t array_ptr[1] = { (uintptr_t)op_6 };
  return (void*)array_ptr[index];
}

void TVMWrapRun() {
  struct Mapped_Feature* accel_fmap_0 = Malloc_Feature(28, 28, 3, 5, 5, 8);
  Map_Feature((char*)input_x, accel_fmap_0);
  struct Conv_Cfg cfg_2 = {3, 64, 28, 32, 2, 3, 3, 1, 1, 0, 0, 1, 1, 26, 26, 28, 18432, 1, 28, 73, 73, 26, 71, 71, 1, 32, 32};
  struct Mapped_Feature* conv_2 = Malloc_Feature(26, 26, 32, 4, 4, 8);
  FPGA_Conv(cfg_2, 0, 0, 0, accel_fmap_0, accel_wmap_1, conv_2);
  Free_Feature(accel_fmap_0);
  struct Conv_Cfg cfg_4 = {32, 64, 26, 64, 2, 3, 3, 1, 1, 0, 0, 1, 1, 24, 24, 26, 36864, 1, 26, 78, 78, 24, 76, 76, 1, 64, 64};
  struct Mapped_Feature* conv_4 = Malloc_Feature(24, 24, 64, 4, 4, 8);
  FPGA_Conv(cfg_4, 0, 0, 0, conv_2, accel_wmap_3, conv_4);
  Free_Feature(conv_2);
  DLTensor tvm_map_5;
  tvm_map_5.data = (void*)op_5;
  tvm_map_5.ndim = 4;
  tvm_map_5.byte_offset = 0;
  tvm_map_5.dtype = (DLDataType){.code = 2, .bits = 32, .lanes = 1};
  tvm_map_5.device = (DLDevice){.device_type = kDLCPU, .device_id = 0};
  int64_t shape_tvm_map_5[] = {1, 24, 24, 64};
  tvm_map_5.shape = shape_tvm_map_5;
  int64_t stride_tvm_map_5[] = {36864, 1536, 64, 1};
  tvm_map_5.strides = stride_tvm_map_5;
  DeMap_Feature(conv_4, (char*)tvm_map_5.data);
  Free_Feature(conv_4);
  DLTensor tvm_6;
  tvm_6.data = (void*)op_6;
  tvm_6.ndim = 4;
  tvm_6.byte_offset = 0;
  tvm_6.dtype = (DLDataType){.code = 2, .bits = 32, .lanes = 1};
  tvm_6.device = (DLDevice){.device_type = kDLCPU, .device_id = 0};
  int64_t shape_tvm_6[] = {1, 64, 24, 24};
  tvm_6.shape = shape_tvm_6;
  int64_t stride_tvm_6[] = {36864, 576, 24, 1};
  tvm_6.strides = stride_tvm_6;
  TVMValue tvalue_6[2];
  int32_t arg_type_ids_6[2] = {3, 3};
  tvalue_6[0].v_handle = &tvm_map_5;
  tvalue_6[1].v_handle = &tvm_6;
  tvm_extern6(tvalue_6, arg_type_ids_6);
}