// generated by codegen c++ csb head at 2024-04-13 21:18:32
// weight storage define
static uint8_t* weight0 = (uint8_t*)0x040000000; // storage size: 2304 B
// runtime storage define
static uint8_t* runtime0 = (uint8_t*)0x040000900; // storage size: 4096 B
static uint8_t* runtime1 = (uint8_t*)0x040001900; // storage size: 57600 B

// get input ptr
uint64_t data = 0x040000900;

// get output ptr
uint64_t output = 0x040001900;

// get weight ddr ptr
uint64_t weight = 0x040000000;

// get weight hbm ptr


// mod init


void main_test(HANDLE device) {
#ifdef REGS_DEBUG
LARGE_INTEGER start_cfg;
LARGE_INTEGER stop_cfg;
LARGE_INTEGER start_run;
LARGE_INTEGER stop_run;
LARGE_INTEGER freq;
double time_sec0;
double time_sec1;
QueryPerformanceFrequency(&freq);
#endif
// accel.sparse.conv2d accel operator node, storage data in runtime1 with 0 offset
#ifdef REGS_DEBUG
QueryPerformanceCounter(&start_cfg);
#endif
  CSB_Write(device, 2, 1);
  CSB_Write(device, 3, 1);
  CSB_Write(device, 4, 32);
  CSB_Write(device, 5, 32);
  CSB_Write(device, 6, 1024);
  CSB_Write(device, 7, 1);
  CSB_Write(device, 8, 1);
  CSB_Write(device, 31, 0);
  CSB_Write(device, 41, 0);
  CSB_Write(device, 42, 0);
  CSB_Write(device, 43, 1);
  CSB_Write(device, 9, 0);
  CSB_Write(device, 10, 0);
  CSB_Write(device, 11, 1);
  CSB_Write(device, 12, 1);
  CSB_Write(device, 13, 3);
  CSB_Write(device, 14, 3);
  CSB_Write(device, 15, 30);
  CSB_Write(device, 16, 900);
  CSB_Write(device, 17, 30);
  CSB_Write(device, 18, 64);
  CSB_Write(device, 19, 16);
  CSB_Write(device, 33, 225);
  CSB_Write(device, 34, 2147483648);
  CSB_Write(device, 35, 3600);
  CSB_Write(device, 36, 120);
  CSB_Write(device, 38, 1);
  CSB_Write(device, 39, 7);
  CSB_Write(device, 40, 4);
  CSB_Write(device, 20, 0);
  CSB_Write(device, 21, 4096);
  CSB_Write(device, 22, 128);
  CSB_Write(device, 23, 4608);
  CSB_Write(device, 32, 576);
  CSB_Write(device, 24, 536870912);
  CSB_Write(device, 25, 0);
  CSB_Write(device, 26, 4);
  CSB_Write(device, 0, 31);
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_cfg);
QueryPerformanceCounter(&start_run);
#endif
  while(CSB_Read(device, 37) != 1) {}
#ifdef REGS_DEBUG
QueryPerformanceCounter(&stop_run);
time_sec0 = (unsigned long long)(stop_cfg.QuadPart - start_cfg.QuadPart) / (double)freq.QuadPart;
time_sec1 = (unsigned long long)(stop_run.QuadPart - start_run.QuadPart) / (double)freq.QuadPart;
printf("accel.sparse.conv2d cfg reg time = %fs \n",time_sec0);
printf("accel.sparse.conv2d run time     = %fs \n",time_sec1);
#endif
}