// generated by python at 2023-11-15 23:42:55
// inputs payload and payload_size
int input_payload = 0;
int input_payload_size = 32768;
int l_bias_payload = 32768;
int l_bias_payload_size = 256;

// output payload and payload_size
int output_payload = 65792;
int output_payload_size = 32768;

// "model_test" layer wrapper function
void layer_norm_0(HANDLE device) {
  CSB_Write(device, 194, 32768);
  CSB_Write(device, 195, 0);
  CSB_Write(device, 196, 16384);
  CSB_Write(device, 197, 16384);
  CSB_Write(device, 198, 33024);
  CSB_Write(device, 199, 16384);
  CSB_Write(device, 200, 16384);
  CSB_Write(device, 201, 2);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, 256);
  CSB_Write(device, 210, 204800);
  CSB_Write(device, 211, 256);
  CSB_Write(device, 220, 0);
  CSB_Write(device, 222, 1);
  CSB_Write(device, 192, 32);
  while (CSB_Read(device, 193) != 1) { }
  CSB_Write(device, 218, 0);
  CSB_Write(device, 192, 64);
  while (CSB_Read(device, 193) != 1) { }
}
void softmax_1(HANDLE device) {
  CSB_Write(device, 195, 33024);
  CSB_Write(device, 196, 16384);
  CSB_Write(device, 197, 16384);
  CSB_Write(device, 198, 65792);
  CSB_Write(device, 199, 16384);
  CSB_Write(device, 200, 16384);
  CSB_Write(device, 201, 2);
  CSB_Write(device, 202, 1);
  CSB_Write(device, 203, 256);
  CSB_Write(device, 211, 256);
  CSB_Write(device, 215, 64);
  CSB_Write(device, 192, 8);
  while (CSB_Read(device, 193) != 1) { }
}

// "model_test" model wrapper function
void model_test(HANDLE device) {
  layer_norm_0(device);
  softmax_1(device);
} 
