git diff ./tb/testbench_LN.sv ../hbm1203/tb/testbench_LN.sv
git diff ./tb/testbench_ACT.sv ../hbm1203/tb/testbench_ACT.sv
git diff ./tb/testbench_HBM_FC.sv ../hbm1203/tb/testbench_HBM_FC.sv
git diff ./tb/testbench_HBM_MVM.sv ../hbm1203/tb/testbench_HBM_MVM.sv
git diff ./tb/testbench_SOFTMAX.sv ../hbm1203/tb/testbench_SOFTMAX.sv
git diff ./tb/testbench_HBM_FC_BN.sv ../hbm1203/tb/testbench_HBM_FC_BN.sv
git diff ./tb/testbench_HBM_MVM_bn.sv ../hbm1203/tb/testbench_HBM_MVM_bn.sv
git diff ./tb/testbench_ElementWise.sv ../hbm1203/tb/testbench_ElementWise.sv
git diff ./tb/testbench_HBM_FC_BN_RES.sv ../hbm1203/tb/testbench_HBM_FC_BN_RES.sv
git diff ./tb/testbench_TRANSPOSE_HBM.sv ../hbm1203/tb/testbench_TRANSPOSE_HBM.sv
git diff ./tb/testbench_HBM_MVM_bn_res.sv ../hbm1203/tb/testbench_HBM_MVM_bn_res.sv
git diff ./tb/testbench_Feature2Weight_HBM.sv ../hbm1203/tb/testbench_Feature2Weight_HBM.sv
git diff ./include/tasks_LN.vh ../hbm1203/include/tasks_LN.vh
git diff ./include/tasks_ACT.vh ../hbm1203/include/tasks_ACT.vh
git diff ./include/tasks_SOFTMAX.vh ../hbm1203/include/tasks_SOFTMAX.vh
git diff ./include/tasks_TRANSPOSE_HBM.vh ../hbm1203/include/tasks_TRANSPOSE_HBM.vh
git diff ./include/tasks_driver_HBM_FC.vh ../hbm1203/include/tasks_driver_HBM_FC.vh
git diff ./include/tasks_driver_HBM_MVM.vh ../hbm1203/include/tasks_driver_HBM_MVM.vh
git diff ./include/tasks_driver_HBM_FC_BN.vh ../hbm1203/include/tasks_driver_HBM_FC_BN.vh
git diff ./include/tasks_driver_HBM_MVM_bn.vh ../hbm1203/include/tasks_driver_HBM_MVM_bn.vh
git diff ./include/tasks_Feature2Weight_HBM.vh ../hbm1203/include/tasks_Feature2Weight_HBM.vh
git diff ./include/tasks_driver_ElementWise.vh ../hbm1203/include/tasks_driver_ElementWise.vh
git diff ./include/tasks_driver_HBM_FC_BN_RES.vh ../hbm1203/include/tasks_driver_HBM_FC_BN_RES.vh
git diff ./include/tasks_driver_HBM_MVM_bn_res.vh ../hbm1203/include/tasks_driver_HBM_MVM_bn_res.vh
