// generated by fcompile.codegen.CCodeGen at 2023-10-28 00:13:17
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include <faccel.h>

static uint8_t* input_data;
static const uint8_t* const_attn_q_weight;
static struct Mapped_Weight* accel_wmap_1;
static const uint8_t* const_attn_k_weight;
static struct Mapped_Weight* accel_wmap_4;
static const uint8_t* const_const4;
static struct Mapped_Weight* accel_wmap_8;
static const uint8_t* const_attn_v_weight;
static struct Mapped_Weight* accel_wmap_12;
static uint8_t* output_16;

void TVMWrapInit() {
  input_data = (uint8_t*)malloc(4096);
  accel_wmap_1 = Malloc_Weight(1, 1, 64, 64, 11, 8);
  input_data = (uint8_t*)malloc(4096);
  accel_wmap_4 = Malloc_Weight(1, 1, 64, 64, 12, 8);
  accel_wmap_8 = Malloc_Weight(1, 1, 64, 64, 8, 8);
  input_data = (uint8_t*)malloc(4096);
  accel_wmap_12 = Malloc_Weight(1, 1, 64, 64, 11, 8);
  output_16 = (uint8_t*)malloc(4096);
}

void TVMWrapSetParams(char* params) {
  const_attn_q_weight = (uint8_t*)params; params += 4096;
  Map_Weight((char*)const_attn_q_weight, accel_wmap_1);
  const_attn_k_weight = (uint8_t*)params; params += 4096;
  Map_Weight((char*)const_attn_k_weight, accel_wmap_4);
  const_const4 = (uint8_t*)params; params += 4096;
  Map_Weight((char*)const_const4, accel_wmap_8);
  const_attn_v_weight = (uint8_t*)params; params += 4096;
  Map_Weight((char*)const_attn_v_weight, accel_wmap_12);
}

// input 0: (1, 1, 64, 64)
void* TVMWrapGetInputPtr(int index) {
  uintptr_t array_ptr[1] = { (uintptr_t)input_data };
  return (void*)array_ptr[index];
}

// output 0: (1, 1, 64, 64)
void* TVMWrapGetOutputPtr(int index) {
  uintptr_t array_ptr[1] = { (uintptr_t)output_16 };
  return (void*)array_ptr[index];
}

void TVMWrapRun() {
struct timespec begin, end;

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Feature* accel_fmap_0 = Malloc_Feature(1, 64, 64, 5, 5, 8);
  Map_Feature((char*)input_data, accel_fmap_0);
  clock_gettime(CLOCK_REALTIME, &end);
  long seconds = end.tv_sec - begin.tv_sec;
  long nanoseconds = end.tv_nsec - begin.tv_nsec;
  double elapsed = seconds + nanoseconds*1e-9;
  printf("Finish accel_fmap_0 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_2 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_2 = Malloc_Feature(1, 64, 64, 8, 8, 8);
  FPGA_Conv(cfg_2, 0, 0, 0, accel_fmap_0, accel_wmap_1, conv_2);
  Free_Feature(accel_fmap_0);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_2 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Feature* accel_fmap_3 = Malloc_Feature(1, 64, 64, 5, 5, 8);
  Map_Feature((char*)input_data, accel_fmap_3);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish accel_fmap_3 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_5 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_5 = Malloc_Feature(1, 64, 64, 8, 8, 8);
  FPGA_Conv(cfg_5, 0, 0, 0, accel_fmap_3, accel_wmap_4, conv_5);
  Free_Feature(accel_fmap_3);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_5 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Weight* tp_6 = Malloc_Weight(1, 64, 64, 8, 8, 8);
  FPGA_Run_Transpose(conv_5, tp_6, 0);
  Free_Feature(conv_5);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish tp_6 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_7 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_7 = Malloc_Feature(1, 64, 64, 9, 9, 8);
  FPGA_Conv(cfg_7, 0, 0, 0, conv_2, tp_6, conv_7);
  Free_Feature(conv_2);
  Free_Weight(tp_6);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_7 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_9 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_9 = Malloc_Feature(1, 64, 64, 6, 6, 8);
  FPGA_Conv(cfg_9, 0, 0, 0, conv_7, accel_wmap_8, conv_9);
  Free_Feature(conv_7);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_9 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Feature* softmax_10 = Malloc_Feature(1, 64, 64, 10, 10, 8);
  FPGA_Run_Softmax(conv_9, softmax_10, 64, 64, 0);
  Free_Feature(conv_9);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish softmax_10 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Feature* accel_fmap_11 = Malloc_Feature(1, 64, 64, 5, 5, 8);
  Map_Feature((char*)input_data, accel_fmap_11);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish accel_fmap_11 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_13 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_13 = Malloc_Feature(1, 64, 64, 8, 8, 8);
  FPGA_Conv(cfg_13, 0, 0, 0, accel_fmap_11, accel_wmap_12, conv_13);
  Free_Feature(accel_fmap_11);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_13 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Mapped_Weight* accel_wmap_14 = Malloc_Weight(1, 1, 64, 64, 8, 8);
  Convert_F2W(conv_13, accel_wmap_14);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish accel_wmap_14 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  struct Conv_Cfg cfg_15 = {64, 64, 64, 64, 0, 1, 1, 1, 1, 0, 0, 1, 1, 64, 1, 64, 4096, 1, 1, 32, 32, 1, 32, 32, 1, 64, 64};
  struct Mapped_Feature* conv_15 = Malloc_Feature(1, 64, 64, 11, 11, 8);
  FPGA_Conv(cfg_15, 0, 0, 0, softmax_10, accel_wmap_14, conv_15);
  Free_Feature(softmax_10);
  Free_Weight(accel_wmap_14);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish conv_15 op takes: %fs\n\n", elapsed);

  clock_gettime(CLOCK_REALTIME, &begin);
  DeMap_Feature(conv_15, (char*)output_16);
  Free_Feature(conv_15);
  clock_gettime(CLOCK_REALTIME, &end);
  seconds = end.tv_sec - begin.tv_sec;
  nanoseconds = end.tv_nsec - begin.tv_nsec;
  elapsed = seconds + nanoseconds*1e-9;
  printf("Finish output_16 op takes: %fs\n\n", elapsed);
}
