// generated by fcompile.codegen.CIRCodeGen at 2023-12-21 15:16:27
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

static uint8_t x[128*2];
static uint8_t w[128*256*2];
static uint8_t r[256*2];
void CONV(short* data, short* weight, short* result, int H, int W, int C, int O, int OH, int OW, int K, int P, int S);
void FC(short* data, short* weight, short* result, int H, int C, int O);

void TVMWrapInit() {

}

void* TVMWrapGetInputPtr(int index) {
  uintptr_t array_ptr[2] = { (uintptr_t)x, (uintptr_t)w };
  return (void*)array_ptr[index];
}

void* TVMWrapGetOutputPtr(int index) {
  uintptr_t array_ptr[3] = { (uintptr_t)x, (uintptr_t)w, (uintptr_t)r };
  return (void*)array_ptr[index];
}

void TVMWrapRun() {
    FC((short*)x, (short*)w, (short*)r, 1, 3, 2);
}
